/**
 * PHASE 9 QUICK REFERENCE CARD
 * 
 * Files Created/Modified & Key Functions
 */

// ╔════════════════════════════════════════════════════════════════════════════╗
// ║ BACKEND: Message Classification                                           ║
// ╚════════════════════════════════════════════════════════════════════════════╝

// File: backend/src/ai/orchestrator/classifier.js (237 lines)

import { classifyMessage } from './classifier.js';

// Classify a user message to determine which agent should handle it
const result = await classifyMessage(
  "I haven't been sleeping well",
  userMemory,      // optional: user context
  'mental-health'  // optional: previous pillar for continuity
);

// Returns: { pillar: 'sleep', confidence: 0.92, reason: '...', method: 'keyword' }

// Available Pillars: sleep, fitness, mental-health, nutrition, finances, 
//                    physical-health, social, spirituality


// ╔════════════════════════════════════════════════════════════════════════════╗
// ║ BACKEND: Crisis Detection & Safety                                        ║
// ╚════════════════════════════════════════════════════════════════════════════╝

// File: backend/src/ai/orchestrator/crisisCheck.js (290 lines)

import { performCrisisCheck, formatCrisisResponse } from './crisisCheck.js';

// Check if message contains crisis indicators
const check = await performCrisisCheck("I want to hurt myself", 'us');

// Returns: {
//   isCrisis: true,
//   severity: 'high',
//   type: 'self_harm',
//   message: 'I\'m concerned about your safety...',
//   resources: [
//     { name: 'Crisis Text Line', number: 'Text HOME to 741741', ... },
//     { name: 'National Suicide Prevention Lifeline', number: '988', ... },
//     ...
//   ]
// }

// Format for API response
const apiResponse = formatCrisisResponse(check);
// Returns: { ok: true, isCrisis: true, severity, type, message, resources, timestamp }


// ╔════════════════════════════════════════════════════════════════════════════╗
// ║ FRONTEND: AI Client for Orchestrator Communication                        ║
// ╚════════════════════════════════════════════════════════════════════════════╝

// File: src/api/aiClient.js (430 lines)

import * as aiClient from '@/api/aiClient';

// ─────────────────────────────────────────────────────────────────────────────
// 1. Send a message to the orchestrator
// ─────────────────────────────────────────────────────────────────────────────

const response = await aiClient.sendMessage({
  message: "I've been feeling anxious lately",
  pillar: "mental-health",  // optional - auto-detected if not provided
  lastMessages: []          // optional - conversation history
});

// Success response:
// {
//   ok: true,
//   text: "I understand anxiety can be...",
//   agent: "mental-health",
//   pillar: "mental-health",
//   model: "claude-3.5-sonnet"
// }

// Crisis response:
// {
//   ok: true,
//   isCrisis: true,
//   severity: "critical",
//   type: "suicide",
//   message: "I hear that you're in pain...",
//   resources: [...],
//   timestamp: "2025-12-03T..."
// }

// Error response (service unavailable):
// {
//   ok: false,
//   error: true,
//   message: "AI temporarily unavailable",
//   fallback: true,
//   suggestion: "Consider journaling your thoughts or reaching out to a friend..."
// }

// ─────────────────────────────────────────────────────────────────────────────
// 2. Save a plan generated by AI
// ─────────────────────────────────────────────────────────────────────────────

const planResult = await aiClient.savePlan({
  title: "30-Day Fitness Challenge",
  content: "...",
  pillar: "fitness",
  pillars: ["fitness", "physical-health"],  // optional: multiple pillars
  timeframe: "1 month"
});

// Returns: { ok: true, item, itemId }

// ─────────────────────────────────────────────────────────────────────────────
// 3. Save a goal
// ─────────────────────────────────────────────────────────────────────────────

const goalResult = await aiClient.saveGoal({
  title: "Run a 5K",
  description: "Complete a 5K race by summer",
  pillar: "fitness",
  criteria: ["Can run 3 miles continuously", "Sub-30 minute time"],  // optional
  deadline: new Date('2025-12-31'),  // optional
  priority: "high"
});

// Returns: { ok: true, item, itemId }

// ─────────────────────────────────────────────────────────────────────────────
// 4. Save a habit
// ─────────────────────────────────────────────────────────────────────────────

const habitResult = await aiClient.saveHabit({
  title: "Morning meditation",
  description: "10-minute guided meditation",
  pillar: "mental-health",
  frequency: "daily",  // or 'weekly', 'monthly'
  targetCount: 1,
  timeOfDay: "06:00"  // optional: preferred time
});

// Returns: { ok: true, item, itemId }

// ─────────────────────────────────────────────────────────────────────────────
// 5. Save a journal entry or log
// ─────────────────────────────────────────────────────────────────────────────

const entryResult = await aiClient.saveEntry({
  title: "Today's reflection",
  content: "Today I realized...",
  pillar: "mental-health",
  type: "journal",  // or 'reflection', 'note'
  metrics: { mood: 8, energy: 7 }  // optional
});

// Returns: { ok: true, item, itemId }

// ─────────────────────────────────────────────────────────────────────────────
// 6. Utility functions
// ─────────────────────────────────────────────────────────────────────────────

// Reset user memory for a pillar
await aiClient.resetMemory('fitness');  // or null for all

// Get user memory/context
const memory = await aiClient.getMemory('mental-health');


// ╔════════════════════════════════════════════════════════════════════════════╗
// ║ FRONTEND: Component Usage Patterns                                         ║
// ╚════════════════════════════════════════════════════════════════════════════╝

// Pattern 1: Handle all response types in a component
// ──────────────────────────────────────────────────

import * as aiClient from '@/api/aiClient';
import { toast } from 'sonner';

const handleSendMessage = async (message) => {
  const response = await aiClient.sendMessage({ message });
  
  if (response.isCrisis) {
    // Show crisis modal with resources
    showCrisisModal(response);
  } else if (response.error) {
    // Show fallback suggestion
    toast.error(response.message);
    console.info('Suggestion:', response.suggestion);
  } else {
    // Display normal response
    displayAgentMessage(response.text, response.agent);
  }
};

// Pattern 2: Save insights from AI (as in AIInsights component)
// ──────────────────────────────────────────────────────────────

const handleSavePlan = async () => {
  if (!insights?.suggested_plan) return;
  
  const result = await aiClient.savePlan({
    title: insights.suggested_plan.title,
    content: insights.suggested_plan.description,
    pillar: insights.focus_area || 'mental-health',
    timeframe: '1 month'
  });

  if (result.ok) {
    toast.success('Plan saved to My Plans!');
  } else {
    toast.error('Failed to save plan');
  }
};

// Pattern 3: Save multiple items in parallel
// ────────────────────────────────────────────

const results = await Promise.all([
  aiClient.savePlan(planData),
  aiClient.saveGoal(goalData),
  aiClient.saveHabit(habitData)
]);

const allSuccess = results.every(r => r.ok);
if (allSuccess) {
  toast.success('All items saved successfully! 🎉');
}


// ╔════════════════════════════════════════════════════════════════════════════╗
// ║ BACKEND INTEGRATION: aiRoutes.js Updates                                  ║
// ╚════════════════════════════════════════════════════════════════════════════╝

// Add these imports to backend/routes/aiRoutes.js:

import { classifyMessage } from '../src/ai/orchestrator/classifier.js';
import { performCrisisCheck, formatCrisisResponse } from '../src/ai/orchestrator/crisisCheck.js';
import { northstarOrchestrator } from '../src/ai/orchestrator/northstarOrchestrator.js';
import aiItems from '../services/aiItems.js';

// Update the /chat endpoint:

router.post('/chat', jwtAuthMiddleware, rateLimiter, async (req, res) => {
  try {
    const { message, pillar, lastMessages } = req.body;
    
    // ✓ STEP 1: Crisis safety check (highest priority)
    const crisisCheck = await performCrisisCheck(message);
    if (crisisCheck.isCrisis) {
      return res.status(200).json(formatCrisisResponse(crisisCheck));
    }
    
    // ✓ STEP 2: Auto-classify message if pillar not provided
    const targetPillar = pillar || (await classifyMessage(message)).pillar;
    
    // ✓ STEP 3: Route to appropriate agent
    const response = await northstarOrchestrator({
      userId: req.userId,
      message,
      explicitPillar: targetPillar,
      lastMessages
    });
    
    res.json(response);
  } catch (error) {
    res.status(503).json({ error: true, message: 'AI temporarily unavailable' });
  }
});

// Add item save endpoints:

router.post('/items/plan', jwtAuthMiddleware, async (req, res) => {
  const { title, content, pillar, pillars, timeframe } = req.body;
  const result = await aiItems.saveLifePlan(req.userId, pillar, 
    { title, content, pillars, timeframe });
  res.json(result);
});

router.post('/items/goal', jwtAuthMiddleware, async (req, res) => {
  const { title, description, pillar, criteria, deadline, priority } = req.body;
  const result = await aiItems.saveGoal(req.userId, pillar,
    { title, description, criteria, deadline, priority });
  res.json(result);
});

router.post('/items/habit', jwtAuthMiddleware, async (req, res) => {
  const { title, description, pillar, frequency, targetCount, timeOfDay } = req.body;
  const result = await aiItems.saveHabit(req.userId, pillar,
    { title, description, frequency, targetCount, timeOfDay });
  res.json(result);
});

router.post('/items/entry', jwtAuthMiddleware, async (req, res) => {
  const { title, content, pillar, type, metrics } = req.body;
  const result = await aiItems.saveEntry(req.userId, pillar,
    { title, content, type, metrics });
  res.json(result);
});


// ╔════════════════════════════════════════════════════════════════════════════╗
// ║ TESTING: Quick Examples                                                   ║
// ╚════════════════════════════════════════════════════════════════════════════╝

// Test 1: Classification accuracy
const testMessages = [
  { msg: "I can't sleep", expected: 'sleep' },
  { msg: "I'm feeling anxious", expected: 'mental-health' },
  { msg: "How do I save money?", expected: 'finances' },
  { msg: "Should I start exercising?", expected: 'fitness' }
];

for (const test of testMessages) {
  const result = await classifyMessage(test.msg);
  console.log(`"${test.msg}" → ${result.pillar} (confidence: ${result.confidence})`);
}

// Test 2: Crisis detection
const crisisTests = [
  "I want to hurt myself",
  "I'm going to call 911",
  "I've overdosed on pills",
  "I'm having a panic attack"  // might not trigger (severity: none)
];

for (const msg of crisisTests) {
  const check = await performCrisisCheck(msg);
  console.log(`"${msg}" → Crisis: ${check.isCrisis} (severity: ${check.severity})`);
}

// Test 3: Frontend flow
const response = await aiClient.sendMessage({
  message: "How do I manage stress?"
});

console.log('Response:', response);
// Expected: { ok: true, text: '...', agent: 'mental-health', pillar: 'mental-health' }


// ╔════════════════════════════════════════════════════════════════════════════╗
// ║ FILES MANIFEST                                                             ║
// ╚════════════════════════════════════════════════════════════════════════════╝

/*
NEW FILES:
  backend/src/ai/orchestrator/classifier.js ........... 237 lines
  backend/src/ai/orchestrator/crisisCheck.js ......... 290 lines
  src/api/aiClient.js .............................. 430 lines
  backend/PHASE_9_IMPLEMENTATION_GUIDE.js ........... Full guide

UPDATED:
  src/ai/AIInsights.jsx ............................ +150 lines
  src/ai/AIContentButtons.jsx ...................... +15 lines
  backend/routes/aiRoutes.js ..................... See integration code above
*/

// ╔════════════════════════════════════════════════════════════════════════════╗
// ║ KEY ENDPOINTS                                                              ║
// ╚════════════════════════════════════════════════════════════════════════════╝

/*
POST /api/orchestrator/chat
  Body: { message, pillar?, lastMessages? }
  Returns: { ok, text?, agent?, pillar?, isCrisis?, resources?, error?, suggestion? }

POST /api/orchestrator/items/plan
  Body: { title, content, pillar, pillars?, timeframe }
  Returns: { ok, item, itemId }

POST /api/orchestrator/items/goal
  Body: { title, description, pillar, criteria?, deadline?, priority? }
  Returns: { ok, item, itemId }

POST /api/orchestrator/items/habit
  Body: { title, description, pillar, frequency, targetCount?, timeOfDay? }
  Returns: { ok, item, itemId }

POST /api/orchestrator/items/entry
  Body: { title, content, pillar, type?, metrics? }
  Returns: { ok, item, itemId }

POST /api/orchestrator/memory/reset
  Body: { pillar? }
  Returns: { ok, message }

GET /api/orchestrator/memory/:pillar
  Returns: { ok, memory }
*/

console.log(`
✅ PHASE 9 Quick Reference Card
All functions, patterns, and integration code documented above.
For full details: backend/PHASE_9_IMPLEMENTATION_GUIDE.js
`);
