export const MISSION_CONTROL_MODULES = {
  CRISIS_MODE: "CRISIS_MODE",
  SMART_NOTIFICATIONS: "SMART_NOTIFICATIONS",
  GOAL_ROADMAP: "GOAL_ROADMAP",
  NEXT_BEST_STEP: "NEXT_BEST_STEP",
  QUICK_ACTIONS: "QUICK_ACTIONS",
  DAILY_READINESS: "DAILY_READINESS",
  PILLAR_PROGRESS: "PILLAR_PROGRESS",
  STREAK_TRACKER: "STREAK_TRACKER",

  // Canonical IDs for currently implemented Mission Control modules
  PRIORITY_ACTION: "PRIORITY_ACTION",
  EMPTY_STATE_GUIDANCE: "EMPTY_STATE_GUIDANCE",
  NARRATIVE_INSIGHT: "NARRATIVE_INSIGHT",
  OVERALL_SCORE: "OVERALL_SCORE",
  PILLAR_OVERVIEW: "PILLAR_OVERVIEW",
  MOMENTUM: "MOMENTUM",
  SUPPORT: "SUPPORT",
  AI_ENTRY: "AI_ENTRY",
};
