export const MISSION_CONTROL_MODULES = {
  CRISIS_MODE: "CRISIS_MODE",
  SMART_NOTIFICATIONS: "SMART_NOTIFICATIONS",
  GOAL_ROADMAP: "GOAL_ROADMAP",
  NEXT_BEST_STEP: "NEXT_BEST_STEP",
  QUICK_ACTIONS: "QUICK_ACTIONS",
  DAILY_READINESS: "DAILY_READINESS",
  PILLAR_PROGRESS: "PILLAR_PROGRESS",
  STREAK_TRACKER: "STREAK_TRACKER",
};
